# Generated by Django 3.2.19 on 2023-06-28 09:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название тега', max_length=50, unique=True, verbose_name='Название тега')),
                ('color', models.CharField(help_text='Цветовой HEX-код (например, #49B64E)', max_length=7, unique=True, validators=[django.core.validators.RegexValidator(message='Введите значение цвета в формате HEX! Пример:#FF0000', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')], verbose_name='Цвет в формате HEX-кода')),
                ('slug', models.SlugField(help_text='Введите slug - идентификатор', unique=True, verbose_name='Slug - идентификатор')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['name'], name='tags_tag_name_3fbe74_idx'),
        ),
    ]
