# Generated by Django 4.2.2 on 2023-06-14 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_username_follow_follow_unique_users'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique_users',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('user', 'author'), name='unique_users', violation_error_message={'unique': 'Такая комбинация пользователей уже существует.'}),
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(check=models.Q(('user', models.F('author')), _negated=True), name='different_users', violation_error_message={'check': 'Автор и подписчик должны быть разными людьми.'}),
        ),
    ]
