# Generated by Django 4.2.2 on 2023-06-12 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['name'], 'verbose_name': 'Рецепт', 'verbose_name_plural': 'Рецепты'},
        ),
        migrations.RemoveIndex(
            model_name='recipe',
            name='foodgram_re_title_b6ebb2_idx',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='unit_of_measure',
            new_name='measurement_unit',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='time_minutes',
            new_name='cooking_time',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='description',
            new_name='text',
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['name'], name='foodgram_re_name_d80ff8_idx'),
        ),
    ]
