# Generated by Django 4.2.2 on 2023-06-16 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image_base64',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
