# Generated by Django 4.2.2 on 2023-06-16 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0002_recipe_image_base64'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='image_base64',
        ),
    ]
