# Generated by Django 4.2.2 on 2023-06-20 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0004_alter_recipe_cooking_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='quantity',
            new_name='amount',
        ),
    ]
