# Generated by Django 4.2.2 on 2023-06-22 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0007_remove_favorite_foodgram_fa_user_id_5d2e53_idx_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='favorite',
            name='unique_favorite',
        ),
        migrations.RemoveConstraint(
            model_name='shoppingcart',
            name='shopping_recipe_user',
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('recipe', 'user'), name='unique_favorite', violation_error_message='Такой рецепт уже есть в "Избранном".'),
        ),
        migrations.AddConstraint(
            model_name='shoppingcart',
            constraint=models.UniqueConstraint(fields=('recipe', 'user'), name='shopping_recipe_user', violation_error_message='Такой рецепт уже есть в "Списке покупок".'),
        ),
    ]
